### ISSUE TITLE
Some questions about the results

### ISSUE THREAD

**Issue by 2916850681** [Walstruzz/edge_eval_python#1]
hello，
evaling the result of edge by python is a good thing，which can help us get rid of Matlab
But,the result of your code is different from Matlab
Has this ever happened to you?
I'd appreciate it if you can give me some help

**Comment by Walstruzz** [comment]
Sorry, could you show more detial?

**Comment by Walstruzz** [comment]
I currently only test my code on hed results. 
Give me some other examples and I'll locate the problem as soon as possible. :)

**Comment by 2916850681** [comment]
hello,
for the same edge result,the eval method(written by Matlab) provided by&nbsp;https://github.com/xwjabc/hed and yours will get different result.


the result above is produced&nbsp;by&nbsp; matlab ( I get it from https://github.com/xwjabc/hed)


while the result below is produced by your method



The edge have been evaluated are attached


Looking forward to your reply


Archer Lee







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Walstruzz/edge_eval_python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Walstruzz/edge_eval_python] Some questions about the results (#1)





 
Sorry, could you show more detial?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

mat.zip (114.33M, 2021年04月17日 17:03 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0b316365e390b89eceaab8c81035504952075255570201001a50005d5318565f06504e0400545a4b0e05025d05545450015000563632620b56454d1f5f45625b&code=71ce65bf

**Comment by Walstruzz** [comment]
Sorry, currently I have another more important task. 
I will check and fix it as soon as possible.

**Comment by 2916850681** [comment]
&nbsp;I would appreciate it&nbsp;if you tell me the result after you&nbsp;Figure out why.
waiting for&nbsp;your good news



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 22, 2021 22:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Walstruzz/edge_eval_python] Some questions about the results (#1)




 
Sorry, currently I have another more important task.
 I will check and fix it as soon as possible.

**Comment by Walstruzz** [comment]
It's just some indexing errors. I will update the code this afternoon.

**Comment by Walstruzz** [comment]
It's just some indexing errors. I will update the code today.

**Comment by 2916850681** [comment]
&nbsp;Thanks a lot.



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 13, 2021 10:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Walstruzz/edge_eval_python] Some questions about the results (#1)




 
It's just some indexing errors. I will update the code this afternoon.
