### ISSUE TITLE
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by onceone** [Walstruzz/edge_eval_python#3]
您好，报如下错误，请问该如何解决？谢谢啦
`OSError: [WinError 193] %1 不是有效的 Win32 应用程序。`
![image](https://user-images.githubusercontent.com/49474255/112783968-11e0e900-9083-11eb-8afd-a51b8f63cc17.png)

**Comment by Walstruzz** [comment]
目前只支持Linux

**Comment by onceone** [comment]
好的，感谢回复。

**Comment by AlbertTJU** [comment]
你好，请问想在windows上运行这个非极大值抑制的程序，该如何操作呢？
