### ISSUE TITLE
使用中的的一些问题

### ISSUE THREAD

**Issue by manguoooneil** [Walstruzz/edge_eval_python#5]
作者您好，我按照您在另一个issue中的回答，将其用于评价自己的数据集。
result_dir是模型预测的路径，gt_dir是label的路径，save_dir用于存放非极大值抑制后的结果,我理解的应该没问题吧。
但是会报以下错误：
edges_eval_dir.py 中 110行左右的compute_rpf函数，报’int' object is not subscriptable
将参数cnt_sum_r_p输出出来显示值为0，很奇怪，请问作者可以提供一些指导吗？

**Comment by pu-1** [comment]
你好，我遇到了相同的问题，请问你是怎么解决的。
