### ISSUE TITLE
Error in NMS Process one image

### ISSUE THREAD

**Issue by Arka161** [Walstruzz/edge_eval_python#6]
I get the error: 

```
malloc(): invalid next size (unsorted)
```

I have converted my result images to the `.mat` format and I'm trying your code, and I get this error. I just used the following to convert my images to `.mat`: 

```
from scipy.io import savemat
import numpy as np
import cv2
import matplotlib.pyplot as plt
img = cv2.imread('2018.png', 0) 

key = "result"
savemat("2018.mat", {key: img})
```

Do you find any issue/bug in this? Thanks

**Comment by WCJ1998** [comment]
Hello, I also encountered such a problem, have you solved this problem?

**Comment by Arka161** [comment]
@WCJ1998 Yes, normalize the images by 255 and make sure each single pixel value ranges between 0 and 1.

**Comment by Aitong1018** [comment]
hello，I converted the pixel values to between 0 and 1, but I still have this error
