### ISSUE TITLE
Encountered an error while performing evaluation

### ISSUE THREAD

**Issue by ZhenjiangFan** [Walstruzz/edge_eval_python#7]
Thank you for your work.

I got an error while using this command "python main.py --alg "HED" --model_name_list "hed" --result_dir edge_result --gt_dir data/groundTruth --file_format .mat". The error looks like this: "*** Error in `python': malloc(): memory corruption: 0x000055c648620ef0 ***".

I could not figure out what is causing the error. I am using Python 3.7. I am wondering if you had had this problem before? If not, do you have any idea what might cause this problem?

Thank you.

**Comment by Arka161** [comment]
Your error probably comes if your images are not normalized by 255. Let me know if that helps.

**Comment by ZhenjiangFan** [comment]
Thank you for taking time to look at my question.

Do you mean I should normalize my edge output result file (e.g. a .mat file) before calling or inside of the nms_process_one_image() function?

Another question about the NMS procedure. I know Canny has NMS as a part of its procedure. Do you think I should perform NMS if I would evaluate Canny's output result?

I do have another question about the function. In the function, you call the C implementation of CSA solver and you pass three matrices to the function. One of them is called "out". From what I observed, the memory problem may be caused by the conversion between Python objects and C++ objects. After calling solver.nms, are you sure the "out" variable holds the NMS result, or are you sure we can use it?


Thank you.

Fan

**Comment by ZhenjiangFan** [comment]
Thank you for taking the time to look at my question.

I divided the input image by 255 before the NMS procedure and it worked. Thank you.

Another question about the NMS procedure. I know Canny has NMS as a part of its procedure. Do you think I should perform NMS if I would evaluate Canny's output result?

Thank you.

Fan

**Comment by Arka161** [comment]
Happy to have helped! 

You wouldn't need to do an additional NMS, if you're using some out-of-the-box Canny implementation from a library (eg: OpenCV).

**Comment by ZhenjiangFan** [comment]
Thank you for your time.
